print("************************************* [Building SConsEx/testing/numerics_tests]")

import os

# Setup environment
env = Environment()

# Settings

# Base source files

SourceFiles = [
   'main.cpp'
]

# Build ...

Program('numerics_tests',SourceFiles)

