print("************************************* [Building SConsEx/testing]")

import os
Import('env')

# Ordered build ...
Scripts = [
   'core_tests/SConstruct',
   'numerics_tests/SConstruct'
]

for script in Scripts:
   SConscript( script )

